### ISSUE TITLE
Bot broken?

### ISSUE THREAD

**Issue by cfilorvyls** [DarylPinto/stickers-for-discord#2]
The bot can recognize commands for stickers and delete the command, but it won't post anything. No problem with roles and other things from my server

**Comment by cfilorvyls** [comment]
My server got a general chat channel where we do most of the talking, and a few other rarely used channels. A week ago the bot stopped working in the general channel, as in i typed :[stickername]:, and then my chat was deleted, but the bot didn't post anything after. 

I did some testing around yesterday and found out that the bot is working on other channels. Tried resetting the roles in my general channel, but the bot still won't work, so i just made a new general chat channel and deleted the old one. The bot works on the new channel. No idea what caused the problem.

**Comment by DarylPinto** [comment]
Hm, I can't say I've ever seen anything like this happen. I just created a [support server](https://discord.gg/HNFmKsE), so if you're able to join and discuss the problem with me a bit further that'd be extremely helpful.
